basePath: /
definitions:
  handlers.userBalanceResp:
    properties:
      balance:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: welcome@adklyuev.ru
    name: Aleksey Klyuev
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger User-balance service API
  version: 0.0.1
paths:
  /users/{id}/balance:
    get:
      consumes:
      - application/json
      description: get balance by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.userBalanceResp'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Show an account balance
      tags:
      - Balance
swagger: "2.0"
